# Steps of Machine Learning
'''
7 Steps of Machine Learning:

1. Data Collection. ...
2. Data Preparation. ...
3. Choose a Model / Algorithm. ...
4. Training the Model. ...
5. Evaluate the Model. ...
6. Parameter Tuning. ...
7. Make Predictions.

'''